from bs4 import BeautifulSoup

htmlMap = """<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="Scan007.jpg" usemap="#image-map">

<map name="image-map">
    <area target="" alt="go-back" title="go-back" href="" coords="998,4494,6325,5100" shape="rect">
    <area target="" alt="chest" title="chest" href="" coords="918,2337,2166,3215" shape="rect">
    <area target="" alt="window" title="window" href="" coords="1023,816,2290,1824" shape="rect">
    <area target="" alt="mouse" title="mouse" href="" coords="5992,2528,6325,2856" shape="rect">
</map>
"""

def parseMap(htmlMap):
    soup = BeautifulSoup(htmlMap)
    image = soup.find('img').attrs['src']
    areas = []
    areasHtml = soup.find_all('area') 
    for areaHtml in areasHtml:
        name = areaHtml.attrs['title']
        coords = areaHtml.attrs['coords']
        shape = areaHtml.attrs['shape']
        areas.append({  'name':     name,
                        'coords':   coords,
                        'shape':    shape})
    return (image, areas)

def toCamelCase(name):
    words = name.split('-')
    result = words[0]
    for i in range(len(words) - 1):
        result += words[i+1][0].upper() + words[i+1][1:]
    return result

image, areas = parseMap(htmlMap)

print("""<link rel="stylesheet" href="style.css">
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script type="text/javascript" src="./image-map-resizer/js/imageMapResizer.min.js"></script>
<script type="text/javascript" src="./howler/dist/howler.js"></script>
<script type="text/javascript" src="./script.js"></script>
<script type="text/javascript" src="./sounds.js"></script>
""")

print(f"""<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="img/{image}" width="100%" usemap="#image-map">

<map name="image-map">""")

for area in areas:
    print(f"""  <area id="{area['name']}" target="" alt="{area['name']}" title="" href="" coords="{area['coords']}" shape="{area['shape']}">""")
print("</map>")

print(f"""
<script type="text/javascript">
    window.addEventListener("DOMContentLoaded", () => {{
""")

for area in areas:
    print(f"""      const {toCamelCase(area['name'])} = document.querySelector("#{area['name']}");""")

print("")

for area in areas:
    print(f"""      {toCamelCase(area['name'])}.addEventListener("click", (e) => {{
            console.log("{toCamelCase(area['name'])} clicked!");
            e.preventDefault();          
        }});""")

print(f"""    }});
</script>""")