from bs4 import BeautifulSoup

htmlMap = """<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="Scan009.jpg" usemap="#image-map">

<map name="image-map">
    <area target="" alt="go-back" title="go-back" href="" coords="389,1811,2544,2142" shape="rect">
    <area target="" alt="closet" title="closet" href="" coords="170,544,756,955" shape="rect">
    <area target="" alt="carpet" title="carpet" href="" coords="975,1249,1545,1603" shape="rect">
    <area target="" alt="flying-bat" title="flying-bat" href="" coords="504,960,936,1281" shape="rect">
    <area target="" alt="sitting-bat" title="sitting-bat" href="" coords="1191,669,1284,820" shape="rect">
</map>
"""

def parseMap(htmlMap):
    soup = BeautifulSoup(htmlMap)
    image = soup.find('img').attrs['src']
    areas = []
    areasHtml = soup.find_all('area') 
    for areaHtml in areasHtml:
        name = areaHtml.attrs['title']
        coords = areaHtml.attrs['coords']
        shape = areaHtml.attrs['shape']
        areas.append({  'name':     name,
                        'coords':   coords,
                        'shape':    shape})
    return (image, areas)

def toCamelCase(name):
    words = name.split('-')
    result = words[0]
    for i in range(len(words) - 1):
        result += words[i+1][0].upper() + words[i+1][1:]
    return result

image, areas = parseMap(htmlMap)

print("""<link rel="stylesheet" href="style.css">
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script type="text/javascript" src="./image-map-resizer/js/imageMapResizer.min.js"></script>
<script type="text/javascript" src="./howler/dist/howler.js"></script>
<script type="text/javascript" src="./sounds.js"></script>
""")

print(f"""<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="img/{image}" width="100%" usemap="#image-map">

<map name="image-map">""")

for area in areas:
    print(f"""  <area id="{area['name']}" target="" alt="{area['name']}" title="" href="" coords="{area['coords']}" shape="{area['shape']}">""")
print("""</map>

<div class="key-container">
    <img  src="img/ScanKeyBlue.png" id="blue-key">
    <img  src="img/ScanKeyGreen.png" id="green-key">
    <img  src="img/ScanKeyPurple.png" id="purple-key">
    <img  src="img/ScanKeyOrange.png" id="orange-key">
</div>""")

print("""<script>
    $('map').imageMapResize();
</script>
""");

print(f"""
<script type="text/javascript">
    window.addEventListener("DOMContentLoaded", () => {{
""")

for area in areas:
    print(f"""      const {toCamelCase(area['name'])} = document.querySelector("#{area['name']}");""")

print("")

for area in areas:
    print(f"""      {toCamelCase(area['name'])}.addEventListener("click", (e) => {{
            console.log("{toCamelCase(area['name'])} clicked!");
            e.preventDefault();
        }});""")

print(f"""    }});
</script>""")